# Generated by Django 4.1.5 on 2023-01-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='details',
            field=models.CharField(default='Our service is quick', max_length=500),
            preserve_default=False,
        ),
    ]
